//
//  Student.swift
//  On the Map
//
//  Created by leanne on 6/30/16.
//  Copyright © 2016 leanne63. All rights reserved.
//

import Foundation

/// Stores student-entered map information from Parse
struct StudentInformation {
	
	/// The date when the student location was created.
	var createdAt: String
	/// The first name of the student which matches their Udacity profile first name.
	var firstName: String
	/// The last name of the student which matches their Udacity profile last name.
	var lastName: String
	/// The latitude of the student location (ranges from -90 to 90).
	var latitude: Double
	/// The longitude of the student location (ranges from -180 to 180).
	var longitude: Double
	/// The location string used for geocoding the student location.
	var mapString: String
	/// The URL provided by the student.
	var mediaURL: String
	/// An auto-generated id/key generated by Parse which uniquely identifies a StudentLocation.
	var objectId: String
	/// An extra (optional) key used to uniquely identify a StudentLocation (Udacity User ID).
	var uniqueKey: String
	/// The date when the student location was last updated.
	var updatedAt: String
	
	
	// MARK: - Initializer
	
	/// Initializer for Dictionary object
	init(_ studentInfo: [String: AnyObject]) {
		
		createdAt = studentInfo[StudentInformationModel.createdAtKey] != nil ? studentInfo[StudentInformationModel.createdAtKey] as! String : ""
		firstName = studentInfo[StudentInformationModel.firstNameKey] as! String
		lastName  = studentInfo[StudentInformationModel.lastNameKey]  as! String
		latitude  = studentInfo[StudentInformationModel.latitudeKey]  as! Double
		longitude = studentInfo[StudentInformationModel.longitudeKey] as! Double
		mapString = studentInfo[StudentInformationModel.mapStringKey] as! String
		mediaURL  = studentInfo[StudentInformationModel.mediaURLKey]  as! String
		objectId  = studentInfo[StudentInformationModel.objectIdKey] != nil ? studentInfo[StudentInformationModel.objectIdKey] as! String : ""
		uniqueKey = studentInfo[StudentInformationModel.uniqueKeyKey] as! String
		updatedAt = studentInfo[StudentInformationModel.updatedAtKey] != nil ? studentInfo[StudentInformationModel.updatedAtKey] as! String : ""
	}
}

