//
//  Student.swift
//  On the Map
//
//  Created by leanne on 6/30/16.
//  Copyright © 2016 leanne63. All rights reserved.
//

import Foundation

/// Stores student-entered map information from Parse
struct StudentInformation {
	
	/// The date when the student location was created.
	let createdAt: String
	/// The first name of the student which matches their Udacity profile first name.
	let firstName: String
	/// The last name of the student which matches their Udacity profile last name.
	let lastName: String
	/// The latitude of the student location (ranges from -90 to 90).
	let latitude: Float
	/// The longitude of the student location (ranges from -180 to 180).
	let longitude: Float
	/// The location string used for geocoding the student location.
	let mapString: String
	/// The URL provided by the student.
	let mediaURL: String
	/// An auto-generated id/key generated by Parse which uniquely identifies a StudentLocation.
	let objectID: String
	/// An extra (optional) key used to uniquely identify a StudentLocation (Udacity User ID).
	let uniqueKey: String
	/// The date when the student location was last updated.
	let updatedAt: String
	
	
	// MARK: - Initializer
	
	init(_ studentInfo: [String: AnyObject]) {
		
		createdAt = studentInfo[StudentInformationModel.createdAtKey] as! String
		firstName = studentInfo[StudentInformationModel.firstNameKey] as! String
		lastName  = studentInfo[StudentInformationModel.lastNameKey]  as! String
		latitude  = studentInfo[StudentInformationModel.latitudeKey]  as! Float
		longitude = studentInfo[StudentInformationModel.longitudeKey] as! Float
		mapString = studentInfo[StudentInformationModel.mapStringKey] as! String
		mediaURL  = studentInfo[StudentInformationModel.mediaURLKey]  as! String
		objectID  = studentInfo[StudentInformationModel.objectIDKey] != nil ? studentInfo[StudentInformationModel.createdAtKey] as! String : ""
		uniqueKey = studentInfo[StudentInformationModel.uniqueKeyKey] as! String
		updatedAt = studentInfo[StudentInformationModel.updatedAtKey] as! String
		
		StudentInformationModel.students.append(self)
		
	}

}
