//
//  Student.swift
//  On the Map
//
//  Created by leanne on 6/30/16.
//  Copyright © 2016 leanne63. All rights reserved.
//

import Foundation

/// Stores student-entered map information from Parse
struct StudentInformation {
	
	/// The date when the student location was created.
	var createdAt: String
	/// The first name of the student which matches their Udacity profile first name.
	var firstName: String
	/// The last name of the student which matches their Udacity profile last name.
	var lastName: String
	/// The latitude of the student location (ranges from -90 to 90).
	var latitude: Double
	/// The longitude of the student location (ranges from -180 to 180).
	var longitude: Double
	/// The location string used for geocoding the student location.
	var mapString: String
	/// The URL provided by the student.
	var mediaURL: String
	/// An auto-generated id/key generated by Parse which uniquely identifies a StudentLocation.
	var objectId: String
	/// An extra (optional) key used to uniquely identify a StudentLocation (Udacity User ID).
	var uniqueKey: String
	/// The date when the student location was last updated.
	var updatedAt: String
	
	
	// MARK: - Initializer
	
	/// Initializer for Dictionary object
	init(_ studentInfo: [String: AnyObject]) {
		
		let createdAtVal = studentInfo[StudentInformationModel.createdAtKey]
		createdAt = createdAtVal as? String ?? ""
		
		let firstNameVal = studentInfo[StudentInformationModel.firstNameKey]
		firstName = firstNameVal as? String ?? ""
		
		let lastNameVal = studentInfo[StudentInformationModel.lastNameKey]
		lastName  = lastNameVal as? String ?? ""
		
		let latitudeVal  = studentInfo[StudentInformationModel.latitudeKey]
		latitude  = latitudeVal as? Double ?? 0.0
		
		let longitudeVal = studentInfo[StudentInformationModel.longitudeKey]
		longitude = longitudeVal as? Double ?? 0.0
		
		let mapStringVal = studentInfo[StudentInformationModel.mapStringKey]
		mapString = mapStringVal as? String ?? ""
		
		let mediaURLVal  = studentInfo[StudentInformationModel.mediaURLKey]
		mediaURL = mediaURLVal as? String ?? ""
		
		let objectIdVal  = studentInfo[StudentInformationModel.objectIdKey]
		objectId = objectIdVal as? String ?? ""
		
		let uniqueKeyVal = studentInfo[StudentInformationModel.uniqueKeyKey]
		uniqueKey = uniqueKeyVal as? String ?? ""
		
		let updatedAtVal = studentInfo[StudentInformationModel.updatedAtKey]
		updatedAt = updatedAtVal as? String ?? ""
	}
}

